### ISSUE TITLE
IIPImage IIIF JPEG2000 with Memcached [A.1]

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#3]
Create a publicly available binary container for easy installation of IIPImage with JPEG2000.

We will use docker to simplify deployment on different machines. The Dockerfile to be in a separate repository.

Basic documentation must be provided in README in the related repository.

**Comment by klokan** [comment]
We have compiled and created a Debian package to simplify the installation of IIIFServer powered by IIPImage JPEG2000 - this is now being used for the ALPHA version of this project.

The build for the latest version of IIPImage is made @klokantech automatically.

Download link for the use in the ALPHA version of this project:
http://downloads.klokantech.com/iiifserver/iiifserver-1.0.0.debian-wheezy.amd64.deb

**Comment by o1da** [comment]
IIPImage and Memcached are installed on the EC2 machine and set-up to work together. We are testing it now with data on the S3 itself. So basic environment is prepared.

The Image of virtual machine is saved - the AMI identifier and the complete documentation is in the Installation protocol (with restricted access because it contains confidential information):
https://docs.google.com/a/klokantech.com/document/d/1OK0WziJ2Z-_lAiBJcWxRazL5se27OQ7WUcqnpVRE7fg/edit?usp=sharing

**Comment by klokan** [comment]
After todays discussion: the Amazon Machine Image (AMI) allows easy and fast start of the prepared machine (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html) and replaces the docker here. Auto scaling uses strictly AMIs as well.

KlokanTech creates the Docker for IIIFServer production use separately (https://github.com/klokan/iiifserver-build/issues/14).

Regular update of the AMIs from the autocompiled .deb package for debian will be a preferred method of update of the image server software for this project.
