### ISSUE TITLE
Large ingest test

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#38]
An ingest with 100k - 250k items with larger files (10kx10k pixels) - for performance testing of S3FS - especially #16

Lets use the USGS dataset: https://github.com/klokantech/hawk/issues/20#issuecomment-109211671

**Comment by o1da** [comment]
Test was successful, it ingested approx 170k of historical maps. It gives many useful suggestions which we can think about. Nothing have to be done immediately, because any important problem haven't appeared, but for the production environment we should adapt some performance tweaks.

media.embedr.eu runs on the Amazon EC2 t2.medium instance, it has 2 CPU with 4GB of RAM. T2 instances have concept of CPU credits (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-instances.html), it basically means that if you don't need CPU power much you could earn some credits which can be automatically spend for significantly performance boost after. The difference between baseline and peak performance was very surprising for me - same set of images needed approx 15-20s to process (download, convert, compress, upload) one image (more images are processed on same time) in the burst mode and 50-80s on the baseline mode. When you start some larger ingest, EC2 t2 instance probably has some free CPU credits, so ingest runs fast, but after about 1-2 hours constant 100% CPU utilization the credits are gone and ingest becomes really slower. And it stays slow until the end because EC2 instance doesn't have much chance to receive some credits because of the constant 100% CPU utilization. I played with it much (disk I/O, network), but the bottleneck is really CPU performance (convert and kdu_compress takes the longest time from ingestion process).

I tried to run another media.embedr.eu instances as slaves which share Celery queue and ingest items parallel. And this is the way we should go in my point of view, because some dedicated powerful server with 16 CPU or more can be bought too, but it would do nothing in 90% of its expensive time. There is an option to leave it as it is now, but probably nobody wants to wait weeks for large ingests (millions of items). And it runs on the same server which have to quickly respond to requests to oembed, iframe etc.

Process of creation of these ingest slaves is generally easy, it basically means to clone media.embedr.eu instance and change docker-compose to not to use redis database locally but connect to master database instead. I prepared another docker-compose config for these slaves to get rid of locally running redis, flask and nginx, only celery needs to be run there. And the master have to receive connections to redis from outside (properly setup security group is needed here, don't let whole internet to connect to the master redis). It can be made in the form of the separate AMI.

I used 15 T2.medium slaves for this ingest, it produces 120GB of .jp2 images during 24h (I made many tweaks during the ingest, so I don't know preciser time how long it ran). 15 T2.medium instances were unnecessarily powerful at the end. The CPU utilisation of these instances fluctuate much, very likely the source servers with images were bottleneck there and the master T2.medium instance was under heavy load too. It had to serve as redis server for all slaves and it done ingest by itself too. Requests for another embed services were slower too, it was much better when I stopped the ingesting on the master.

With these things on mind it makes sense to use Amazon Auto Scaling to dynamically boost performance and significantly shorten time if the large ingest is being done and scale down to baseline performance when no ingest is running. Do it manually isn't obviously much flexible. So I'm going to create a new issue with this potential enhancement. #55

With this huge dataset I done performance test of the IIIF server too.
`siege -c25 -i -t1h -q -f usgs_test.txt`

```
Transactions:              57614 hits
Availability:             100.00 %
Elapsed time:            3599.70 secs
Data transferred:        3177.10 MB
Response time:              1.06 secs
Transaction rate:          16.01 trans/sec
Throughput:             0.88 MB/sec
Concurrency:               17.00
Successful transactions:       57590
Failed transactions:               0
Longest transaction:           19.26
Shortest transaction:           0.00
```

It ran for 1 hour, utilization of CPU of iiif.embedr.eu was on 100% whole time, but nothing failed and 57614  .jp2 images were downloaded from S3 during this test. It proves that our script for cleaning S3 local cache works fine too #12, because this dataset is many times larger then available space on the IIIF server.
