### ISSUE TITLE
Did the ingestion process break?

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#44]
I've uploaded a test batch (batch 4) containing one file to the ingestion API. It kept the status pending, so I looked at batch 3 which is pending from item 2493 onwards. I believe batch 3 was part of #35 which is closed. 

Does this mean that the ingestion process is just really slow or did one of the parts of ingestion break?

**Comment by o1da** [comment]
After the refactoring during the last night I initiated re run the ingestions number 1 - 3, because data model and communication to cloudsearch was changed. The process was paused in the middle (I don't know why now). I have just restarted docker-compose now and it started to work from the point where it stopped. Only pending tasks are being processed now. For now the 1500 tasks are remaining. Please wait approx. half an hour.

**Comment by mzeinstra** [comment]
Yes, working properly again.
