### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#45]
Today I've been testing ingestion and see how this works. I've noticed that the front-end that is being developed on dev.embedr.eu suffers from slow search results and empty thumbnails. 

Are these two related? Will this also happen when the service is in production?

**Comment by o1da** [comment]
Search performance is out of our control generally, we just fill the data into Amazon CloudSearch service.  Only a few settings can be set there, probably the most interesting option is a type of CloudSearch instance - for now we are using of "search.m3.medium instance" which was the first type, but there are others.

And I have just checked thumbnail issues and realized that you don't use valid ID but CloudSearch hash identifier. This hash is used for modification on CloudSearch itself, but valid item ID is inside the CloudSearch data.

**Comment by mzeinstra** [comment]
Ah I see, but CloudSearch does not run on the same instance as the ingestion?

@tomkr included for the reference to his implementation of CloudSearch.

**Comment by klokan** [comment]
CloudSearch is a service from Amazon - it does not run on our EC2.
@tomkr manages access to CloudSearch API on his own.

More comments here:
- the http://dev.embedr.eu/ submits search query on every key stroke - without any delay. That's not a best practice...
- the http://dev.embedr.eu/ calls immediately for thumbnails. For repeatedly visited items this is going to be fast, but when the image is visited for the first time the IIIF servers are in the background downloading the complete .jp2 file from S3 just to create a thumbnail. It may take some time (cca 200ms extra for each thumbnail) to load - as it is documented in our performance tests from #4: https://docs.google.com/document/d/18YvJ9bf7NH1SrPxARyvcutzkhNVTz42y_KlxOnfYVuI/edit?usp=sharing
- if you want to apply this sort of interface on the 3.000.000 high-res images and have for all of these the fast thumbnails - be prepared to pay for the infrastructure with several IIIF servers behind the load balancer and probably also a dedicated memcached (ElastiCache) shared between the instances. On the performance tuning for the production use there is still a lot of work during the FINAL milestone.
- CloudSearch now contains duplicated items (because of a need for hashed CloudSearch internal IDs as described in #40) and because of the new ingest triggered yesterday night #44 
- We are still going to delete the complete CloudSearch database and all ingested data probably several times before the FINAL milestone. For sure after the ticket #43 is finished - before the DEMO day milestone.

Bugs on dev.embedr.eu should be reported to @tomkr at https://github.com/tomkr/embedr/issues
Closing.

**Comment by mzeinstra** [comment]
Ah I see, I didn't understand the flow behind it. Now I do. Thanks for setting me straight.

**Comment by tomkr** [comment]
Quick comment on the search on every keystroke: this is something that will change, but is very practical for my tests. The final version should search on enter/button click, so that queries can be constructed before being submitted. Good of you to notice though. :+1:
