### ISSUE TITLE
Why is the IIIF image API limited to 1000x1000 pixels?

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#66]
I build a small script for another project that takes random crops of our largest image (http://media.embedr.eu/Rijksmuseum_SK-C-5) of 900x1600 (widescreen in portret mode).

example urls:

```
http://iiif.embedr.eu/Rijksmuseum_SK-C-5/5604,354,3825,6800/900,1600/0/native.jpg
http://iiif.embedr.eu/Rijksmuseum_SK-C-5/7955,2237,4619,8211/900,1600/0/native.jpg
http://iiif.embedr.eu/Rijksmuseum_SK-C-5/2443,304,4813,8556/900,1600/0/native.jpg
http://iiif.embedr.eu/Rijksmuseum_SK-C-5/4052,1154,4625,8222/900,1600/0/native.jpg
http://iiif.embedr.eu/Rijksmuseum_SK-C-5/3982,3257,2881,5121/900,1600/0/native.jpg
http://iiif.embedr.eu/Rijksmuseum_SK-C-5/3650,1290,5997,10661/900,1600/0/native.jpg
http://iiif.embedr.eu/Rijksmuseum_SK-C-5/9309,4439,4123,7329/900,1600/0/native.jpg
http://iiif.embedr.eu/Rijksmuseum_SK-C-5/5558,1021,6146,10926/900,1600/0/native.jpg
http://iiif.embedr.eu/Rijksmuseum_SK-C-5/2292,2745,3239,5758/900,1600/0/native.jpg
http://iiif.embedr.eu/Rijksmuseum_SK-C-5/3147,78,6356,11299/900,1600/0/native.jpg 
```

all of them seemed stretched while the ratio between the selection and the size is the same (0.5625). The actual file being delivered by the API is not 900x1600 as requested but 900x1000 pixels.

If I make the width and height of the size to no larger than 1000 I do get the correct images back. 

compare
http://iiif.embedr.eu/Rijksmuseum_SK-C-5/3147,78,6356,11299/900,1600/0/native.jpg 
to
http://iiif.embedr.eu/Rijksmuseum_SK-C-5/3147,78,6356,11299/450,800/0/native.jpg 

Why do impose this technical limitation, is this a bug or a choice?

**Comment by klokan** [comment]
The maximal request size limit is an option in the configuration of the
IIIFserver - described in the installation protocol.

We can make the limit higher - maybe 2000 pixels?

I would not recommend unlimited request size. On larger files the
tiled viewer approach should be used...

To create a single 3000x3000 pixel image the single process is blocked for
some time and at least 27 MByte of RAM is required (3000x3000x3 bytes).
We may get thousands of such requests per second...

What size limit do you want?

On Wednesday, August 19, 2015, Maarten Zeinstra notifications@github.com
wrote:

> I build a small script for another project that takes random crops of our
> largest image (http://media.embedr.eu/Rijksmuseum_SK-C-5) of 900x1600
> (widescreen in portret mode).
> 
> example urls:
> 
> http://iiif.embedr.eu/Rijksmuseum_SK-C-5/5604,354,3825,6800/900,1600/0/native.jpghttp://iiif.embedr.eu/Rijksmuseum_SK-C-5/7955,2237,4619,8211/900,1600/0/native.jpghttp://iiif.embedr.eu/Rijksmuseum_SK-C-5/2443,304,4813,8556/900,1600/0/native.jpghttp://iiif.embedr.eu/Rijksmuseum_SK-C-5/4052,1154,4625,8222/900,1600/0/native.jpghttp://iiif.embedr.eu/Rijksmuseum_SK-C-5/3982,3257,2881,5121/900,1600/0/native.jpghttp://iiif.embedr.eu/Rijksmuseum_SK-C-5/3650,1290,5997,10661/900,1600/0/native.jpghttp://iiif.embedr.eu/Rijksmuseum_SK-C-5/9309,4439,4123,7329/900,1600/0/native.jpghttp://iiif.embedr.eu/Rijksmuseum_SK-C-5/5558,1021,6146,10926/900,1600/0/native.jpghttp://iiif.embedr.eu/Rijksmuseum_SK-C-5/2292,2745,3239,5758/900,1600/0/native.jpghttp://iiif.embedr.eu/Rijksmuseum_SK-C-5/3147,78,6356,11299/900,1600/0/native.jpg
> 
> all of them seemed stretched while the ratio between the selection and the
> size is the same (0.5625). The actual file being delivered by the API is
> not 900x1600 as requested but 900x1000 pixels.
> 
> If I make the width and height of the size to no larger than 1000 I do get
> the correct images back.
> 
> compare
> 
> http://iiif.embedr.eu/Rijksmuseum_SK-C-5/3147,78,6356,11299/900,1600/0/native.jpg
> to
> 
> http://iiif.embedr.eu/Rijksmuseum_SK-C-5/3147,78,6356,11299/450,800/0/native.jpg
> 
> Why do impose this technical limitation, is this a bug or a choice?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/klokantech/hawk/issues/66.

## 

Petr Pridal, Ph.D.
CEO

Klokan Technologies GmbH
Hofnerstrasse 98, 6314 Unterageri, Switzerland
Tel: +41 (0)41 511 26 12
Email: info@klokantech.com
Web: http://www.klokantech.com/

**Comment by mzeinstra** [comment]
I see you concern and I believe we need to test this in the real world.

For now we need 2560x 2560 images to be possible. We will artificially limit the size in a our user interface. If a power user directly speaks to the IIIF API we will notice in our server load.

I would consider it to be a bug that the service simply replaces the size to 1000 when it went over that limit. If the system has a max capacity it needs to scale back the result, not make it stretched by simply replacing numbers above a 1000 to 1000.

**Comment by klokan** [comment]
I have warned you, this may cause degradation of performance of the service if used heavily by third-parties. Large images should be displayed via tiles - not as a single request.
We will do what you want.

Tasks for us:
- [x] Set limit on 2560 pixels.
- [x] Rebuild the AMI for iiif service
- [x] Update the elastic load-balancer
- [x] Update installation protocol appropriately

Related time to be tracked to the maintenance.

The behaviour (clamping of the larger number) is existing implementation in the open-source iipimage component. It was not implemented by us for the HAWK project. We can reimplement it and make a pull request - but it is not bug we are responsible for, because it is not our code.

Do you want us to work on the improvement of iipimage implementation?
Then we would track the related work under a different ticket.

**Comment by o1da** [comment]
Done and tested.
Check http://iiif.embedr.eu/Rijksmuseum_wiki_SK-C-5/full/full/0/native.jpg it has 2560px width

**Comment by klokan** [comment]
@mzeinstra:

I have check the cropping functionality on http://dev.embedr.eu/...
Are you completely crazy to keep for crop size request for embedding the original pixel size?
You really want to make img src requests with image width 12000 pixels for example?

My comments (and your reactions about "only for power users") on this thread was ignored while implementing the user interface crop functionality...

Exactly for this reason the limit to 1000x1000 pixels was there.

Embedding code like this is a problem of you user interface implementation - intentionally ruining performance of the iiif service by offering people BY DEFAULT completely inappropriate size of the image request. This should be fixed on your side ASAP...

``` html
<div id='embedr_img'><img src='http://iiif.embedr.eu/Rijksmuseum_SK-C-5/1168,799,11929,9105/11929,9105/0/native.jpg'/><p>Detail of 'Militia Company of District II under the Command of Captain Frans Banninck Cocq, Known as the ‘Night Watch’' | Rembrandt Harmensz. van Rijn | <a href='https://www.rijksmuseum.nl/en/explore-the-collection/overview/rembrandt-harmensz-van-rijn/objects#/SK-C-5,1' target='_blank'>Rijksmuseum, Amsterdam</a> | <img src='http://media.embedr.eu/static/img/pd.png' /> <a href='http://creativecommons.org/publicdomain/zero/1.0/'>No rights reserved.</a></p></div> 
```

ehm...

**Comment by mzeinstra** [comment]
@klokan 

I don't understand your argument. 

Are you talking about that the original size is presented here as numbers?
![screen shot 2015-10-28 at 10 01 59](https://cloud.githubusercontent.com/assets/5627431/10783867/09eceeb0-7d5b-11e5-86f7-e4241822731c.png)

That is a bug indeed, and it should be 2560x2560 or 1024 as width.

However we never request the original pixel size. the resulting image is 740kb, not that large. 

How would you see this changed?

**Comment by klokan** [comment]
> That is a bug indeed, and it should be 2560x2560 or 1024 as width.

I would suggest max 1000 px here.

> However we never request the original pixel size. the resulting image is 740kb, not that large.

YOU DO REQUEST THE ORIGINAL PIXEL SIZE! But luckily the server returns only the max width - increased in this ticket from 1000px to 2560px on your request, where you promised:

> For now we need 2560x 2560 images to be possible. **We will artificially limit the size in a our user interface.** If a power user directly speaks to the IIIF API we will notice in our server load.

Copy & paste of automatically generated HTML code is not a power user... 

In the user interface for lame users are now constructed IIIF requests to retrieve an image of size 13823,11336 pixels (because the `13823,11336` is part of URL to the IIIF service). Everybody just copy&paste the code - and practically nobody wants this huge size of the image.

Most of the people embedding an image into webpage or blog may need for sure less then 1000px width - especially on a cropped part of an image. BTW the YouTube embed has default width="560" height="315".

If you provide copy & paste code to people - you have no control over it anymore. It is out there.

If you in future request another increase of this limit - every single copy&pasted embed code will suddenly get even higher image (**change of behaviour - without change of the URL!!!**), and will hit hard our servers if used by thousands of users. There will be no way back from such situation. THIS IS VERY DANGEROUS!

So result:
- the bug in user interface must be fixed
- to prevent this to happen again in future - I sugest we return from IIIFServer an error message telling that requests with pixel size over 2560 are not allowed, better than to return a smaller image. It means all our existing cropped embed code requesting more then the limit will stop to run - because these are wrongly constructed by the user interface as it exists now...

**Comment by mzeinstra** [comment]
@klokan Ah I see, now I understand your initial message. This indeed a bug and I'll take appropriate steps.

As for the IIIF service, that seems like a good error. Is it part of the way IIIF protocol is set up?
