### ISSUE TITLE
Possibility to have @tomkr access to media.embedr.eu server?

### ISSUE THREAD

**Issue by mzeinstra** [klokantech/hawk#74]
@tomkr is hindered by creating blind PR request when making adjustments to the viewer display pages. Is there a way he can run his changes on the media.embedr.eu server?

**Comment by tomkr** [comment]
I don't need access to the server, just a way to locally run the app (and testsuite) on my machine.

**Comment by o1da** [comment]
Info about access to servers is in the Installation protocol.

https://docs.google.com/document/d/1OK0WziJ2Z-_lAiBJcWxRazL5se27OQ7WUcqnpVRE7fg/edit#heading=h.mjh3e7d7thnv

But I would definitely suggest to run project via docker-compose localy (configuration similar to https://github.com/klokantech/hawk/blob/master/docker-compose-local.yml ) from source. With similar configuration it doesn't push anything outside localhost (S3 etc.). And maybe I can send you redis persistent file and sqlite database from live media server and you would have info about all items and  could test on it (against live iiif server) without any ingestion.

**Comment by tomkr** [comment]
I have to admit I'm not a docker expert, but I've tried to start with docker-compose-local.yml. I run into an error pretty quickly. It's probably something simple, but perhaps you could give me a hand.

To get started I run:
`docker-compose -f docker-compose-local.yml up`

The error I get is:
`ingest_1 | [2015-11-26 21:20:07,019: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -2 connecting to redis:6379. Name or service not known..`

Before that though I get the big Redis logo and it says:

```
Running in standalone mode
Port: 6379
PID: 1
```

So that looks good to me at first sight. Any ideas?

**Comment by mzeinstra** [comment]
@tomkr does this block your v1 pull request to @klokan?

**Comment by o1da** [comment]
We have updated readme and configuration for local development, so using it would be more clear and easier now. @tomkr Please try it.

https://github.com/klokantech/embedr/blob/master/README.md
