### ISSUE TITLE
oEmbed provider [B.3]

### ISSUE THREAD

**Issue by klokan** [klokantech/hawk#8]
Prototype correct and valid oEmbed with the help of IIIF - on the gh-pages branch.

Document snippets of the code which needs to be implemented to be eEmbed compliant.

Related documentation:
http://www.oembed.com/
http://en.wikipedia.org/wiki/OEmbed

Verify the static prototype compatibility with WordPress:
https://codex.wordpress.org/Embeds

Target is exact specification for:
- oEmbed provider (at http://embed.europeana.eu/oembed/[UNIQUE-ID]) (static image)
  (for development purpose http://embedhawk.klokantech.com/oembed/[UNIQUE-ID])
  as defined https://github.com/klokantech/hawk/wiki/B.Embed

**Comment by klokan** [comment]
Test with:
http://stackoverflow.com/questions/11835655/how-to-test-oembed-discovery
https://iframely.com

**Comment by o1da** [comment]
Basic oEmbed provider is done. There is a simple configuration:
- URL scheme: `http://embedhawk.klokantech.com/oembed/*`
- API endpoint: `http://embedhawk.klokantech.com/oembedprovider`

oEmbed discovery is implemented too.

It can be checked in wordpress. It is needed to add a new oEmbed provider with this function:

`wp_oembed_add_provider( 'http://embedhawk.klokantech.com/oembed/*', http://embedhawk.klokantech.com/oembedprovider' );`

It should be in a theme's **_function.php**_ file and after this modification oEmbed can be put in a custom page with similar code:

`[embed width="100" height="100"]http://embedhawk.klokantech.com/oembed/000-test2[/embed]`

I tried it in my local installation of wordpress and it worked correctly. If you want to try it you should to test it in your worpress too, because the public wordpress demo doesn't allow to change a function.php file so embedhawk.klokantech.com wouldn't be in oEmbed provider white list so it wouldn't work.

https://iframely.com doesn't support to change oEmbed provider list in easy way and it doesn't support oEmbed discovery too, so better pages to check it online are these:
- http://embed.ly/docs/explore/oembed?url=http%3A%2F%2Fembedhawk.klokantech.com%2Foembed%2F16564185666
- http://oembed.frdnspnzr.de/ (put http://embedhawk.klokantech.com/oembed/16564189866 to form)

Or directly check API with some additional parameters (format, widht, heght):
- http://embedhawk.klokantech.com/oembedprovider?format=json&url=http%3A//embedhawk.klokantech.com/oembed/16564189866&maxwidth=800&maxheight=900
- http://embedhawk.klokantech.com/oembedprovider?format=xml&url=http%3A//embedhawk.klokantech.com/oembed/16564189866&maxwidth=800&maxheight=900

I have just added another testing data with id 16564189866 and 16564185666

**Comment by klokan** [comment]
BTW The related Wordpress info about oEmbed Discovery:
https://codex.wordpress.org/Embeds#What_About_oEmbed_Discovery.3F

I am closing this ticket - as the implementation seems to be finished. Thanks @o1da.

@mzeinstra could you please validate? Are you happy with the oEmbed implementation?

**Comment by mzeinstra** [comment]
Hi thanks for this update. 

I do have a few questions after some initial testing.
1. Your initial issues stated that this should be in a different branch than it is in now. Not sure if that is important though.
2. Why is it, that you can set an image max-width and max-height but always refer to the native image file (hardcoded in https://github.com/klokantech/hawk/blob/master/app/templates/oembed_img.html ) Wouldn't that defeat some of its purpose?
3. Is this issue only for the basic oEmbed functionality? We've discussed the need for basic metadata with oEmbed. I do not see any metadata at the moment, if this is dependant on the implementation of the ingestion API and its data model, than that is fine. However we should open a new issue on adding this metadata in this embed functionality.
4. Would it not be possible to embed a region like IIIF offers?

**Comment by klokan** [comment]
@mzeinstra 
Answers:
1. Internal discussion leaded to the direct implementation inside of the master branch.
2. The embedding in oEmbed runs in fact via XML and JSON. The purpose of the template mentioned above is to provide `/ombed/[UNIQUE-ID]` web sites - which in oEmbed are in fact only used for identification of what you want to embed. I am proposing in #29 to get rid of these pages completely and use instead the existing `/[UNIQUE-ID]` with zoomable viewer.
3. Metadata verification to be done across different services in #30 
4. oEmbed does not support regions IMHO
